debug: true
build:
  image: teaci/msys$$arch
  pull: true
  shell: mingw$$arch
  commands:
    - svn co https://github.com/mkae/MINGW-packages/trunk/mingw-w64-libbsdf
    - cd mingw-w64-libbsdf
    - makepkg-mingw -s --noconfirm --skippgpcheck --noprogressbar

# Notifications are according to @fracting broken at this point in time, that's why disable them (was stolen from BSDFProcessor anyways):
#notify:
#  gitter:
#    webhook: https://webhooks.gitter.im/e/d8f2032e40a8e78a3882

matrix:
  arch:
    - 64
    - 32

