language: c++

matrix:
  #allow_failures:
  #  - os: linux
  include:
    - os: linux
      dist: bionic
      sudo: false
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++
            - cmake
            - libeigen3-dev
          update: true
      env:
        - EIGEN3_INCLUDE_DIR="/usr/include/eigen3"
    - os: osx
      sudo: false
      addons:
        homebrew:
          packages:
            - cmake
            - eigen
          update: false
      env:
        - EIGEN3_INCLUDE_DIR="/usr/local/include/eigen3"

script:
  - mkdir build
  - cd build
  - cmake -DEIGEN3_INCLUDE_DIR=$EIGEN3_INCLUDE_DIR ..
  - make -j4
