language: c++

matrix:
  allow_failures:
    - os: osx
  include:
    - os: linux
      dist: trusty
      sudo: required
      #language: c++
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++
            - cmake
            - libeigen3-dev
          update: true
      env:
        - EIGEN3_INCLUDE_DIR="/usr/include/eigen3"
    - os: osx
      #osx_image: xcode11
      sudo: required
      #language: objective-c
      addons:
        homebrew:
          packages:
            - cmake
            - eigen
          update: true
      env:
        - EIGEN3_INCLUDE_DIR="/usr/local/include/eigen3"

script:
  - mkdir build
  - cd build
  - cmake -DEIGEN3_INCLUDE_DIR=$EIGEN3_INCLUDE_DIR ..
  - make -j4
